# <center>Laboratorium 1<br>Metody Numeryczne</center>

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [1]:
import numpy as np
import scipy

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [2]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.

In [3]:
from main import cylinder_area
print(cylinder_area(3, 4.5))
print(cylinder_area(-1, 2.2))

141.3716694115407
nan


Funkcja opiera się na dobrze znanym wzorze na pole powierzchni walca. Import stałej $\pi$ z biblioteki $math$ pozwala znacznie zwiększyć precyzję obliczeń. Funkcja zwraca wartość pola wtedy i tylko wtedy, gdy oba parametry są typu $\textit{float}$ bądź $\textit{int}$ oraz są dodatnie, w przeciwnym wypadku zwracana jest wartość $NaN$.

**_Zadanie 2._**  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji _[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)_ oraz _[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)_. Wypisz go i przeanalizuj otrzymane rezultaty.

In [4]:
a1 = np.arange(3.5, 12, 0.45)
a2 = np.linspace(5.2, 16, num=8)

print(a1)
print('\n')
print(a2)

[ 3.5   3.95  4.4   4.85  5.3   5.75  6.2   6.65  7.1   7.55  8.    8.45
  8.9   9.35  9.8  10.25 10.7  11.15 11.6 ]


[ 5.2         6.74285714  8.28571429  9.82857143 11.37142857 12.91428571
 14.45714286 16.        ]


Funkcja $arrange$ zwraca ciąg arytmetyczny o zadanej przez nas różnicy oraz gwarantuje, że ostatni wyraz tego ciągu będzie mniejszy od wybranej liczby. W przypadku $linspace$ to my determinujemy ilość wyrazów ciągu oraz dokładny przedział, w którym będą się zawierać jego elementy, zaś funkcja automatycznie wylicza krok tego ciągu. $Linspace$ wydaje się być idealnym zastosowaniem dla plotowania funkcji na danym przedziale.

***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [5]:
from main import fib
print("Wartość funkcji dla n = 5: \n {0}".format(fib(5)))
print("Wartość funkcji dla n = 0.5: \n {0}".format(fib(0.5)))

Wartość funkcji dla n = 5: 
 [array([1., 1., 2., 3., 5.])]
Wartość funkcji dla n = 0.5: 
 None


Funkcja zwraca wektor wtedy i tylko wtedy, gdy argument jest typu całkowitego oraz gdy nie jest mniejszy od $1$. Gdy te warunki są spełnione, tworzy wektor jedynek i w pętli przechodzi po niej, wyliczjąc kolejne wyrazy zgodnie z definicją ciągu. Należy uważać, aby nie wyjść poza zakres indeksów dla $n = 1$.

***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [6]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

In [7]:
from main import matrix_calculations
print("Macierz o wyznaczniku różnym od 0: \n")

Minv, Mt, Mdet = matrix_calculations(4)
print("Macierz odwrotna: \n{0}".format(Minv))
print("Macierz transponowana: \n{0}".format(Mt))
print("Wyznacznik macierzy: \n{0}".format(Mdet))

print("\nMacierz o wyznaczniku równym 0: \n")

Minv, Mt, Mdet = matrix_calculations(0)
print("Macierz odwrotna: \n{0}".format(Minv))
print("Macierz transponowana: \n{0}".format(Mt))
print("Wyznacznik macierzy: \n{0}".format(Mdet))

Macierz o wyznaczniku różnym od 0: 

Macierz odwrotna: 
[[ 0.09375  0.53125 -0.15625]
 [ 0.125    0.375    0.125  ]
 [-0.125    0.625   -0.125  ]]
Macierz transponowana: 
[[ 4  0 -4]
 [ 1  1  4]
 [-4  1  1]]
Wyznacznik macierzy: 
-32.0

Macierz o wyznaczniku równym 0: 

Macierz odwrotna: 
nan
Macierz transponowana: 
[[0 0 0]
 [1 1 0]
 [0 1 1]]
Wyznacznik macierzy: 
0.0


Pakiet $numpy$ zawiera w sobie podstawowe operacje na macierzach. Macierz odwrotna możliwa jest do wyznaczenia wtedy i tylko wtedy, gdy wyznacznik tej macierzy jest różny od zera - w przeciwnym wypadku przypisywana jest wartość $NaN$. W pakiecie tym zaimplementowano również przejrzysty i prosty sposób na wypisywanie wektorów bądź macierzy pomagające w demonstracji działania funkcji. Mały detal odnośnie wypisywania: nie należy wstawiać spacji przed wypisywaną macierzą w nowej linii - ma to, w mojej opinii, nadzyczaj negatywny wpływ na estetykę.

In [8]:
demonstrate = np.array([[1, 2], [3, 4]])
print("Bez spacji: \n{0}".format(demonstrate))
print("Ze spacją: \n {0}".format(demonstrate))

Bez spacji: 
[[1 2]
 [3 4]]
Ze spacją: 
 [[1 2]
 [3 4]]


***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [9]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

In [10]:
M = np.array([[3, 1, -2, 4], [0, 1, 1, 5], [-2, 1, 1, 6], [4, 3, 0, 1]])

print("Element M(1,1): \n {0}".format(M[0][0]))
print("Element M(3,3): \n {0}".format(M[2][2]))
print("Element M(3,2): \n {0}".format(M[2][1]))

w1 = M[:, 2]
w2 = M[1, :]

print("Wektor w1: \n {0}".format(w1))
print("Wektor w2: \n {0}".format(w2))

Element M(1,1): 
 3
Element M(3,3): 
 1
Element M(3,2): 
 1
Wektor w1: 
 [-2  1  1  0]
Wektor w2: 
 [0 1 1 5]


Sposób odwoływania się do elementów n-wymiarowej macierzy w $numpy$ jest identyczny jak w tablicach n-wymiarowych. Dodatkowo biblioteka wspiera bardziej zaawansowane opcje odwoływania się do elementów macierzy obecne w języku $Python$ takie jak   $slicing$.

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [11]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


In [12]:
from main import custom_matrix

print(custom_matrix(4, 6))
print(custom_matrix(0.2, 4))

[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 2 2 3 4 5]
 [3 3 3 3 4 5]]
None


Jako, iż indeksowanie jest identyczne wobec wcześniej wspomnianych tablic wielowymiarowych, realizacja przechodzenia po macierzy i edycji jej elementów jest analogiczna do znanych już rozwiązań. Funkcja zwraca wynikową macierz wtedy i tylko wtedy, gdy wymiary macierzy są dodatnimi liczbami całkowitymi typu $int$. Przydatną opcją funkcji inicjalizującej pustą macierz (w tym przypadku $zeros$) jest parametr $dtype$ pozwalający wybrać, jakiego typu danymi zostanie wypełniona macierz.

***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

In [13]:
v1 = np.array([[1], [3], [13]])
v2 = np.array([[8], [5], [-2]])
print("v1 = \n{0}".format(v1))
print("v2 = \n{0}".format(v2))

print("4*v1 = \n{0}".format(4 * v1))
print("-v2 + (2, 2, 2)^T = \n{0}".format(-v2 + 2 * np.ones((3, 1), dtype = int)))

print("Iloczyn v1 i v2 w sensie mnożenia macierzy \n{0}".format(np.dot(v1, v2)))
print("Iloczyn v1 i v2 element-wise: \n{0}".format(np.multiply(v1, v2)))

v1 = 
[[ 1]
 [ 3]
 [13]]
v2 = 
[[ 8]
 [ 5]
 [-2]]
4*v1 = 
[[ 4]
 [12]
 [52]]
-v2 + (2, 2, 2)^T = 
[[-6]
 [-3]
 [ 4]]


ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

Wektorów $v_1$ i $v_2$ nie da się pomnożyć w sensie Cauchy'ego, ponieważ nie pozwalają na to ich wymiary - błąd zwracany przez funkcję był spodziewany.  Niektóre operacje udało się uprościć za pomocą funkcji $ones$.

In [ ]:
nda = np.ndarray(shape=(3,3), dtype=int)
print(nda)
print(nda * v1)
print(nda @ v1)

Przeciążony operator $@$ dla obiektów $ndarray$ reprezentuje klasyczne mnożenie macierzy, zaś $*$ oznacza mnożenie $\textit{element-wise}$. 

***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

In [ ]:
M1 = np.array([[1, -7, 3], [-12, 3, 4], [5, 13, -3]])
print("3*M1 = \n{0}".format(3*M1))
print("3*M1 + macierz jedynek = \n{0}".format(3*M1 + np.ones(3, dtype=int)))
print("Transpozycja macierzy M1: \n{0}".format(np.transpose(M1)))
print("M1 ◦ v1 = \n{0}".format(np.dot(M1, v1)))
print("v2^T ◦ M1 = \n{0}".format(np.dot(np.transpose(v2), M1)))



Operacje mnożenia macierzy przez skalar czy iloczyn macierzy i wektora są wspierane przez $numpy$ - funkcje działają zarówno dla wektorów, jak i macierzy. Liczy się jedynie wymóg kompatybilności wymiarów elementów, który jednak może być czasem ominięty przez $broadcasting$. Ponownie kod można było uprościć za pomocą funkcji $ones$.    

Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)